function(e,s,r,gg){
var z=gz$gwx_12()
var oFM=_mz(z,'image',['mode',0,'src',1,'style',1],[],e,s,gg)
_(r,oFM)
var fGM=_n('view')
_rz(z,fGM,'class',3,e,s,gg)
var oJM=_mz(z,'image',['class',4,'src',1],[],e,s,gg)
_(fGM,oJM)
var cKM=_n('view')
_rz(z,cKM,'class',6,e,s,gg)
var oLM=_v()
_(cKM,oLM)
if(_oz(z,7,e,s,gg)){oLM.wxVkey=1
var lMM=_mz(z,'open-data',['class',8,'style',1,'type',2],[],e,s,gg)
_(oLM,lMM)
}
else{oLM.wxVkey=2
var aNM=_mz(z,'image',['class',11,'src',1],[],e,s,gg)
_(oLM,aNM)
}
oLM.wxXCkey=1
_(fGM,cKM)
var tOM=_n('view')
_rz(z,tOM,'class',13,e,s,gg)
var ePM=_n('view')
_rz(z,ePM,'class',14,e,s,gg)
var oRM=_oz(z,15,e,s,gg)
_(ePM,oRM)
var bQM=_v()
_(ePM,bQM)
if(_oz(z,16,e,s,gg)){bQM.wxVkey=1
var xSM=_n('open-data')
_rz(z,xSM,'type',17,e,s,gg)
_(bQM,xSM)
}
else{bQM.wxVkey=2
var oTM=_n('text')
var fUM=_oz(z,18,e,s,gg)
_(oTM,fUM)
_(bQM,oTM)
}
bQM.wxXCkey=1
_(tOM,ePM)
var cVM=_n('view')
_rz(z,cVM,'class',19,e,s,gg)
var hWM=_oz(z,20,e,s,gg)
_(cVM,hWM)
_(tOM,cVM)
_(fGM,tOM)
var oXM=_n('view')
_rz(z,oXM,'class',21,e,s,gg)
var cYM=_n('view')
_rz(z,cYM,'class',22,e,s,gg)
var oZM=_n('view')
_rz(z,oZM,'class',23,e,s,gg)
var l1M=_n('view')
var a2M=_oz(z,24,e,s,gg)
_(l1M,a2M)
_(oZM,l1M)
var t3M=_n('view')
var e4M=_oz(z,25,e,s,gg)
_(t3M,e4M)
_(oZM,t3M)
_(cYM,oZM)
var b5M=_mz(z,'view',['class',26,'style',1],[],e,s,gg)
var o6M=_n('view')
_rz(z,o6M,'class',28,e,s,gg)
var x7M=_oz(z,29,e,s,gg)
_(o6M,x7M)
_(b5M,o6M)
var o8M=_mz(z,'slider',['activeColor',30,'backgroundColor',1,'bindchange',2,'bindchanging',3,'blockColor',4,'max',5,'min',6,'style',7,'value',8],[],e,s,gg)
_(b5M,o8M)
var f9M=_n('view')
_rz(z,f9M,'class',39,e,s,gg)
var c0M=_oz(z,40,e,s,gg)
_(f9M,c0M)
_(b5M,f9M)
_(cYM,b5M)
_(oXM,cYM)
_(fGM,oXM)
var hAN=_mz(z,'image',['class',41,'src',1],[],e,s,gg)
_(fGM,hAN)
var cHM=_v()
_(fGM,cHM)
if(_oz(z,43,e,s,gg)){cHM.wxVkey=1
var oBN=_mz(z,'button',['bindgetuserinfo',44,'class',1,'openType',2],[],e,s,gg)
var cCN=_n('image')
_rz(z,cCN,'src',47,e,s,gg)
_(oBN,cCN)
var oDN=_n('text')
var lEN=_oz(z,48,e,s,gg)
_(oDN,lEN)
_(oBN,oDN)
_(cHM,oBN)
}
var hIM=_v()
_(fGM,hIM)
if(_oz(z,49,e,s,gg)){hIM.wxVkey=1
var aFN=_mz(z,'button',['bindtap',50,'class',1],[],e,s,gg)
var tGN=_n('image')
_rz(z,tGN,'src',52,e,s,gg)
_(aFN,tGN)
var eHN=_n('text')
var bIN=_oz(z,53,e,s,gg)
_(eHN,bIN)
_(aFN,eHN)
_(hIM,aFN)
}
cHM.wxXCkey=1
hIM.wxXCkey=1
_(r,fGM)
var oJN=_mz(z,'button',['bindtap',54,'class',1,'openType',2,'sessionFrom',3],[],e,s,gg)
var xKN=_oz(z,58,e,s,gg)
_(oJN,xKN)
_(r,oJN)
return r
}