function(e,s,r,gg){
var z=gz$gwx_14()
var bWN=_mz(z,'image',['mode',0,'src',1,'style',1],[],e,s,gg)
_(r,bWN)
var oXN=_n('view')
_rz(z,oXN,'class',3,e,s,gg)
var xYN=_mz(z,'view',['class',4,'style',1],[],e,s,gg)
var oZN=_n('view')
_rz(z,oZN,'class',6,e,s,gg)
var f1N=_oz(z,7,e,s,gg)
_(oZN,f1N)
_(xYN,oZN)
_(oXN,xYN)
_(r,oXN)
var c2N=_n('view')
_rz(z,c2N,'class',8,e,s,gg)
var h3N=_n('view')
_rz(z,h3N,'class',9,e,s,gg)
var o4N=_n('view')
_rz(z,o4N,'class',10,e,s,gg)
var c5N=_oz(z,11,e,s,gg)
_(o4N,c5N)
_(h3N,o4N)
var o6N=_n('view')
_rz(z,o6N,'class',12,e,s,gg)
var l7N=_v()
_(o6N,l7N)
if(_oz(z,13,e,s,gg)){l7N.wxVkey=1
var a8N=_mz(z,'radio-group',['bindchange',14,'data-idx',1],[],e,s,gg)
var t9N=_v()
_(a8N,t9N)
var e0N=function(oBO,bAO,xCO,gg){
var fEO=_n('label')
_rz(z,fEO,'class',20,oBO,bAO,gg)
var cFO=_mz(z,'radio',['checked',21,'style',1,'value',2],[],oBO,bAO,gg)
_(fEO,cFO)
var hGO=_mz(z,'view',['class',24,'style',1],[],oBO,bAO,gg)
var oHO=_oz(z,26,oBO,bAO,gg)
_(hGO,oHO)
_(fEO,hGO)
_(xCO,fEO)
return xCO
}
t9N.wxXCkey=2
_2z(z,18,e0N,e,s,gg,t9N,'label','idx','k')
_(l7N,a8N)
}
l7N.wxXCkey=1
_(h3N,o6N)
_(c2N,h3N)
_(r,c2N)
var cIO=_mz(z,'view',['bindtap',27,'class',1,'id',2],[],e,s,gg)
var oJO=_mz(z,'image',['class',30,'mode',1,'src',2],[],e,s,gg)
_(cIO,oJO)
_(r,cIO)
var lKO=_n('view')
_rz(z,lKO,'class',33,e,s,gg)
var aLO=_mz(z,'button',['bindtap',34,'id',1],[],e,s,gg)
var tMO=_oz(z,36,e,s,gg)
_(aLO,tMO)
_(lKO,aLO)
var eNO=_mz(z,'button',['bindtap',37,'id',1],[],e,s,gg)
var bOO=_oz(z,39,e,s,gg)
_(eNO,bOO)
_(lKO,eNO)
var oPO=_mz(z,'button',['bindtap',40,'id',1],[],e,s,gg)
var xQO=_oz(z,42,e,s,gg)
_(oPO,xQO)
_(lKO,oPO)
_(r,lKO)
var oRO=_mz(z,'qa-picker',['bindconfirm',43,'qaItem',1],[],e,s,gg)
_(r,oRO)
return r
}