function(e,s,r,gg){
var z=gz$gwx_16()
var h1P=_mz(z,'image',['mode',0,'src',1,'style',1],[],e,s,gg)
_(r,h1P)
var o2P=_mz(z,'view',['class',3,'hidden',1],[],e,s,gg)
var c3P=_n('view')
_rz(z,c3P,'class',5,e,s,gg)
var o4P=_mz(z,'image',['class',6,'src',1],[],e,s,gg)
_(c3P,o4P)
var l5P=_n('view')
_rz(z,l5P,'style',8,e,s,gg)
var a6P=_mz(z,'view',['class',9,'hidden',1],[],e,s,gg)
var t7P=_oz(z,11,e,s,gg)
_(a6P,t7P)
_(l5P,a6P)
_(c3P,l5P)
var e8P=_mz(z,'form',['bindsubmit',12,'reportSubmit',1],[],e,s,gg)
var b9P=_mz(z,'view',['class',14,'hidden',1],[],e,s,gg)
var o0P=_oz(z,16,e,s,gg)
_(b9P,o0P)
_(e8P,b9P)
var xAQ=_n('view')
_rz(z,xAQ,'class',17,e,s,gg)
var oBQ=_n('view')
_rz(z,oBQ,'class',18,e,s,gg)
var fCQ=_mz(z,'view',['class',19,'style',1],[],e,s,gg)
var cDQ=_oz(z,21,e,s,gg)
_(fCQ,cDQ)
_(oBQ,fCQ)
var hEQ=_mz(z,'view',['class',22,'style',1],[],e,s,gg)
var oFQ=_mz(z,'input',['bindinput',24,'class',1,'maxlength',2,'placeholder',3,'placeholderClass',4,'type',5,'value',6],[],e,s,gg)
_(hEQ,oFQ)
var cGQ=_n('view')
var oHQ=_oz(z,31,e,s,gg)
_(cGQ,oHQ)
_(hEQ,cGQ)
_(oBQ,hEQ)
_(xAQ,oBQ)
var lIQ=_n('view')
_rz(z,lIQ,'class',32,e,s,gg)
_(xAQ,lIQ)
var aJQ=_n('view')
_rz(z,aJQ,'class',33,e,s,gg)
var tKQ=_n('view')
_rz(z,tKQ,'class',34,e,s,gg)
var eLQ=_oz(z,35,e,s,gg)
_(tKQ,eLQ)
_(aJQ,tKQ)
var bMQ=_mz(z,'view',['class',36,'style',1],[],e,s,gg)
var oNQ=_mz(z,'input',['bindinput',38,'class',1,'cursorSpacing',2,'focus',3,'maxlength',4,'placeholder',5,'placeholderClass',6,'type',7],[],e,s,gg)
_(bMQ,oNQ)
var xOQ=_n('view')
var oPQ=_oz(z,46,e,s,gg)
_(xOQ,oPQ)
_(bMQ,xOQ)
_(aJQ,bMQ)
_(xAQ,aJQ)
var fQQ=_n('view')
_rz(z,fQQ,'class',47,e,s,gg)
_(xAQ,fQQ)
var cRQ=_n('view')
_rz(z,cRQ,'class',48,e,s,gg)
var hSQ=_n('view')
_rz(z,hSQ,'class',49,e,s,gg)
var oTQ=_oz(z,50,e,s,gg)
_(hSQ,oTQ)
_(cRQ,hSQ)
var cUQ=_n('view')
_rz(z,cUQ,'style',51,e,s,gg)
var oVQ=_oz(z,52,e,s,gg)
_(cUQ,oVQ)
_(cRQ,cUQ)
var lWQ=_mz(z,'picker',['bindchange',53,'bindtap',1,'class',2,'range',3,'style',4,'value',5],[],e,s,gg)
var aXQ=_mz(z,'view',['class',59,'style',1],[],e,s,gg)
var tYQ=_n('text')
_rz(z,tYQ,'style',61,e,s,gg)
var eZQ=_oz(z,62,e,s,gg)
_(tYQ,eZQ)
_(aXQ,tYQ)
var b1Q=_oz(z,63,e,s,gg)
_(aXQ,b1Q)
_(lWQ,aXQ)
_(cRQ,lWQ)
var o2Q=_mz(z,'image',['src',64,'style',1],[],e,s,gg)
_(cRQ,o2Q)
_(xAQ,cRQ)
var x3Q=_n('view')
_rz(z,x3Q,'class',66,e,s,gg)
_(xAQ,x3Q)
var o4Q=_n('view')
_rz(z,o4Q,'class',67,e,s,gg)
var f5Q=_n('view')
_rz(z,f5Q,'class',68,e,s,gg)
var c6Q=_oz(z,69,e,s,gg)
_(f5Q,c6Q)
_(o4Q,f5Q)
var h7Q=_mz(z,'picker',['bindchange',70,'bindtap',1,'class',2,'range',3,'style',4,'value',5],[],e,s,gg)
var o8Q=_mz(z,'view',['class',76,'style',1],[],e,s,gg)
var c9Q=_n('text')
var o0Q=_oz(z,78,e,s,gg)
_(c9Q,o0Q)
_(o8Q,c9Q)
_(h7Q,o8Q)
_(o4Q,h7Q)
var lAR=_mz(z,'image',['src',79,'style',1],[],e,s,gg)
_(o4Q,lAR)
_(xAQ,o4Q)
var aBR=_n('view')
_rz(z,aBR,'class',81,e,s,gg)
_(xAQ,aBR)
_(e8P,xAQ)
var tCR=_n('view')
_rz(z,tCR,'class',82,e,s,gg)
var bER=_mz(z,'view',['catchtap',83,'class',1],[],e,s,gg)
var oFR=_n('text')
var xGR=_oz(z,85,e,s,gg)
_(oFR,xGR)
_(bER,oFR)
var oHR=_n('text')
_rz(z,oHR,'hidden',86,e,s,gg)
var fIR=_oz(z,87,e,s,gg)
_(oHR,fIR)
_(bER,oHR)
_(tCR,bER)
var eDR=_v()
_(tCR,eDR)
if(_oz(z,88,e,s,gg)){eDR.wxVkey=1
var cJR=_mz(z,'button',['bindgetuserinfo',89,'class',1,'hoverClass',2,'openType',3],[],e,s,gg)
var hKR=_oz(z,93,e,s,gg)
_(cJR,hKR)
_(eDR,cJR)
}
else{eDR.wxVkey=2
var oLR=_mz(z,'button',['class',94,'formType',1,'hoverClass',2],[],e,s,gg)
var cMR=_oz(z,97,e,s,gg)
_(oLR,cMR)
_(eDR,oLR)
}
eDR.wxXCkey=1
_(e8P,tCR)
_(c3P,e8P)
_(o2P,c3P)
var oNR=_n('view')
_rz(z,oNR,'class',98,e,s,gg)
var lOR=_oz(z,99,e,s,gg)
_(oNR,lOR)
_(o2P,oNR)
_(r,o2P)
var aPR=_mz(z,'modal',['bindconfirm',100,'confirmText',1,'hidden',2,'noCancel',3,'title',4],[],e,s,gg)
var tQR=_n('text')
var eRR=_oz(z,105,e,s,gg)
_(tQR,eRR)
_(aPR,tQR)
_(r,aPR)
return r
}