function(e,s,r,gg){
var z=gz$gwx_22()
var o05=_n('view')
_rz(z,o05,'class',0,e,s,gg)
var lA6=_mz(z,'icon',['size',1,'type',1],[],e,s,gg)
_(o05,lA6)
var aB6=_n('view')
_rz(z,aB6,'class',3,e,s,gg)
var tC6=_oz(z,4,e,s,gg)
_(aB6,tC6)
_(o05,aB6)
var eD6=_n('view')
_rz(z,eD6,'class',5,e,s,gg)
var bE6=_oz(z,6,e,s,gg)
_(eD6,bE6)
_(o05,eD6)
var oF6=_n('view')
_rz(z,oF6,'class',7,e,s,gg)
var xG6=_mz(z,'button',['bindtap',8,'class',1,'type',2],[],e,s,gg)
var oH6=_oz(z,11,e,s,gg)
_(xG6,oH6)
_(oF6,xG6)
_(o05,oF6)
_(r,o05)
return r
}