function(e,s,r,gg){
var z=gz$gwx_9()
var oVH=_n('view')
_rz(z,oVH,'class',0,e,s,gg)
var cWH=_v()
_(oVH,cWH)
if(_oz(z,1,e,s,gg)){cWH.wxVkey=1
var lYH=_n('view')
_rz(z,lYH,'class',2,e,s,gg)
var aZH=_n('view')
_rz(z,aZH,'class',3,e,s,gg)
var b3H=_n('view')
_rz(z,b3H,'class',4,e,s,gg)
var o4H=_n('image')
_rz(z,o4H,'src',5,e,s,gg)
_(b3H,o4H)
_(aZH,b3H)
var x5H=_n('view')
_rz(z,x5H,'class',6,e,s,gg)
var o6H=_oz(z,7,e,s,gg)
_(x5H,o6H)
_(aZH,x5H)
var f7H=_n('view')
_rz(z,f7H,'class',8,e,s,gg)
var c8H=_oz(z,9,e,s,gg)
_(f7H,c8H)
_(aZH,f7H)
var h9H=_n('view')
_rz(z,h9H,'class',10,e,s,gg)
var o0H=_oz(z,11,e,s,gg)
_(h9H,o0H)
_(aZH,h9H)
var t1H=_v()
_(aZH,t1H)
if(_oz(z,12,e,s,gg)){t1H.wxVkey=1
var cAI=_mz(z,'view',['class',13,'style',1],[],e,s,gg)
var oBI=_n('view')
_rz(z,oBI,'class',15,e,s,gg)
var lCI=_v()
_(oBI,lCI)
var aDI=function(eFI,tEI,bGI,gg){
var xII=_mz(z,'image',['class',17,'src',1],[],eFI,tEI,gg)
_(bGI,xII)
return bGI
}
lCI.wxXCkey=2
_2z(z,16,aDI,e,s,gg,lCI,'item','index','')
_(cAI,oBI)
var oJI=_mz(z,'view',['class',19,'style',1],[],e,s,gg)
var fKI=_oz(z,21,e,s,gg)
_(oJI,fKI)
_(cAI,oJI)
_(t1H,cAI)
}
var e2H=_v()
_(aZH,e2H)
if(_oz(z,22,e,s,gg)){e2H.wxVkey=1
var cLI=_n('view')
_rz(z,cLI,'class',23,e,s,gg)
var hMI=_n('view')
_rz(z,hMI,'class',24,e,s,gg)
var oNI=_oz(z,25,e,s,gg)
_(hMI,oNI)
_(cLI,hMI)
var cOI=_n('view')
_rz(z,cOI,'class',26,e,s,gg)
var oPI=_oz(z,27,e,s,gg)
_(cOI,oPI)
_(cLI,cOI)
_(e2H,cLI)
}
t1H.wxXCkey=1
e2H.wxXCkey=1
_(lYH,aZH)
var lQI=_mz(z,'view',['class',28,'id',1],[],e,s,gg)
var aRI=_v()
_(lQI,aRI)
if(_oz(z,30,e,s,gg)){aRI.wxVkey=1
var eTI=_mz(z,'button',['bindgetuserinfo',31,'class',1,'id',2,'openType',3],[],e,s,gg)
var bUI=_mz(z,'image',['mode',35,'src',1,'style',2],[],e,s,gg)
_(eTI,bUI)
_(aRI,eTI)
}
else{aRI.wxVkey=2
var oVI=_mz(z,'button',['bindtap',38,'class',1,'id',2],[],e,s,gg)
var xWI=_mz(z,'image',['mode',41,'src',1,'style',2],[],e,s,gg)
_(oVI,xWI)
_(aRI,oVI)
}
var oXI=_mz(z,'button',['bindcontact',44,'class',1,'openType',2,'sessionFrom',3],[],e,s,gg)
var fYI=_oz(z,48,e,s,gg)
_(oXI,fYI)
_(lQI,oXI)
var tSI=_v()
_(lQI,tSI)
if(_oz(z,49,e,s,gg)){tSI.wxVkey=1
var cZI=_mz(z,'view',['class',50,'style',1],[],e,s,gg)
var h1I=_n('view')
_rz(z,h1I,'class',52,e,s,gg)
var o2I=_oz(z,53,e,s,gg)
_(h1I,o2I)
_(cZI,h1I)
var c3I=_v()
_(cZI,c3I)
var o4I=function(a6I,l5I,t7I,gg){
var b9I=_v()
_(t7I,b9I)
if(_oz(z,56,a6I,l5I,gg)){b9I.wxVkey=1
var o0I=_n('view')
_rz(z,o0I,'class',57,a6I,l5I,gg)
var xAJ=_n('view')
_rz(z,xAJ,'class',58,a6I,l5I,gg)
var oBJ=_mz(z,'image',['bindtap',59,'data-item',1,'src',2],[],a6I,l5I,gg)
_(xAJ,oBJ)
_(o0I,xAJ)
var fCJ=_n('view')
_rz(z,fCJ,'class',62,a6I,l5I,gg)
var cDJ=_oz(z,63,a6I,l5I,gg)
_(fCJ,cDJ)
_(o0I,fCJ)
_(b9I,o0I)
}
b9I.wxXCkey=1
return t7I
}
c3I.wxXCkey=2
_2z(z,54,o4I,e,s,gg,c3I,'item','index','{{index}}')
_(tSI,cZI)
}
aRI.wxXCkey=1
tSI.wxXCkey=1
_(lYH,lQI)
_(cWH,lYH)
}
var oXH=_v()
_(oVH,oXH)
if(_oz(z,64,e,s,gg)){oXH.wxVkey=1
var hEJ=_mz(z,'view',['hidden',65,'style',1],[],e,s,gg)
var oFJ=_v()
_(hEJ,oFJ)
var cGJ=function(lIJ,oHJ,aJJ,gg){
var eLJ=_n('view')
_rz(z,eLJ,'class',69,lIJ,oHJ,gg)
var bMJ=_n('view')
var oNJ=_v()
_(bMJ,oNJ)
if(_oz(z,71,lIJ,oHJ,gg)){oNJ.wxVkey=1
var xOJ=_n('view')
_rz(z,xOJ,'class',72,lIJ,oHJ,gg)
var cRJ=_n('view')
_rz(z,cRJ,'class',73,lIJ,oHJ,gg)
var hSJ=_mz(z,'view',['class',74,'style',1],[],lIJ,oHJ,gg)
var oTJ=_n('view')
_rz(z,oTJ,'style',76,lIJ,oHJ,gg)
var cUJ=_mz(z,'view',['class',77,'style',1],[],lIJ,oHJ,gg)
var oVJ=_mz(z,'image',['class',79,'mode',1,'src',2],[],lIJ,oHJ,gg)
_(cUJ,oVJ)
_(oTJ,cUJ)
var lWJ=_n('view')
_rz(z,lWJ,'class',82,lIJ,oHJ,gg)
var aXJ=_n('view')
_(lWJ,aXJ)
_(oTJ,lWJ)
var tYJ=_mz(z,'view',['class',83,'style',1],[],lIJ,oHJ,gg)
var eZJ=_n('view')
_rz(z,eZJ,'style',85,lIJ,oHJ,gg)
var b1J=_oz(z,86,lIJ,oHJ,gg)
_(eZJ,b1J)
_(tYJ,eZJ)
var o2J=_n('view')
_rz(z,o2J,'style',87,lIJ,oHJ,gg)
var x3J=_n('view')
_rz(z,x3J,'class',88,lIJ,oHJ,gg)
var o4J=_v()
_(x3J,o4J)
var f5J=function(h7J,c6J,o8J,gg){
var o0J=_mz(z,'view',['bindtap',92,'data-ansNo',1,'data-answer',2,'data-ques',3,'style',4],[],h7J,c6J,gg)
var lAK=_n('view')
_rz(z,lAK,'class',97,h7J,c6J,gg)
var aBK=_oz(z,98,h7J,c6J,gg)
_(lAK,aBK)
_(o0J,lAK)
_(o8J,o0J)
return o8J
}
o4J.wxXCkey=2
_2z(z,91,f5J,lIJ,oHJ,gg,o4J,'obj','ansNo','')
_(o2J,x3J)
_(tYJ,o2J)
_(oTJ,tYJ)
_(hSJ,oTJ)
var tCK=_n('view')
_rz(z,tCK,'class',99,lIJ,oHJ,gg)
_(hSJ,tCK)
_(cRJ,hSJ)
_(xOJ,cRJ)
var oPJ=_v()
_(xOJ,oPJ)
if(_oz(z,100,lIJ,oHJ,gg)){oPJ.wxVkey=1
var eDK=_n('view')
_rz(z,eDK,'class',101,lIJ,oHJ,gg)
var bEK=_n('view')
_rz(z,bEK,'class',102,lIJ,oHJ,gg)
var oFK=_n('view')
_rz(z,oFK,'class',103,lIJ,oHJ,gg)
_(bEK,oFK)
var xGK=_n('view')
var oHK=_n('view')
_rz(z,oHK,'style',104,lIJ,oHJ,gg)
var fIK=_n('view')
_rz(z,fIK,'class',105,lIJ,oHJ,gg)
var cJK=_oz(z,106,lIJ,oHJ,gg)
_(fIK,cJK)
_(oHK,fIK)
var hKK=_n('view')
_rz(z,hKK,'class',107,lIJ,oHJ,gg)
var oLK=_n('view')
_(hKK,oLK)
_(oHK,hKK)
_(xGK,oHK)
_(bEK,xGK)
var cMK=_mz(z,'image',['class',108,'mode',1,'src',2],[],lIJ,oHJ,gg)
_(bEK,cMK)
_(eDK,bEK)
_(oPJ,eDK)
}
var fQJ=_v()
_(xOJ,fQJ)
if(_oz(z,111,lIJ,oHJ,gg)){fQJ.wxVkey=1
var oNK=_n('view')
_rz(z,oNK,'class',112,lIJ,oHJ,gg)
var lOK=_n('view')
_rz(z,lOK,'class',113,lIJ,oHJ,gg)
var aPK=_mz(z,'view',['class',114,'style',1],[],lIJ,oHJ,gg)
var tQK=_mz(z,'image',['class',116,'mode',1,'src',2],[],lIJ,oHJ,gg)
_(aPK,tQK)
_(lOK,aPK)
var eRK=_n('view')
var bSK=_n('view')
_rz(z,bSK,'style',119,lIJ,oHJ,gg)
var oTK=_n('view')
_rz(z,oTK,'class',120,lIJ,oHJ,gg)
var xUK=_n('view')
_(oTK,xUK)
_(bSK,oTK)
var oVK=_mz(z,'view',['class',121,'style',1],[],lIJ,oHJ,gg)
var fWK=_oz(z,123,lIJ,oHJ,gg)
_(oVK,fWK)
_(bSK,oVK)
_(eRK,bSK)
_(lOK,eRK)
var cXK=_n('view')
_rz(z,cXK,'class',124,lIJ,oHJ,gg)
_(lOK,cXK)
_(oNK,lOK)
_(fQJ,oNK)
}
oPJ.wxXCkey=1
fQJ.wxXCkey=1
_(oNJ,xOJ)
}
oNJ.wxXCkey=1
_(eLJ,bMJ)
_(aJJ,eLJ)
return aJJ
}
oFJ.wxXCkey=2
_2z(z,68,cGJ,e,s,gg,oFJ,'item','i','')
_(oXH,hEJ)
}
cWH.wxXCkey=1
oXH.wxXCkey=1
_(r,oVH)
return r
}