function(e,s,r,gg){
var z=gz$gwx_1()
var oB=_mz(z,'view',['class',0,'hidden',1],[],e,s,gg)
var xC=_n('view')
_rz(z,xC,'class',2,e,s,gg)
var oD=_n('view')
_rz(z,oD,'class',3,e,s,gg)
var fE=_oz(z,4,e,s,gg)
_(oD,fE)
_(xC,oD)
var cF=_n('view')
_rz(z,cF,'class',5,e,s,gg)
var hG=_oz(z,6,e,s,gg)
_(cF,hG)
_(xC,cF)
var oH=_n('view')
_rz(z,oH,'class',7,e,s,gg)
var cI=_mz(z,'button',['bindgetuserinfo',8,'class',1,'openType',2,'type',3],[],e,s,gg)
var oJ=_oz(z,12,e,s,gg)
_(cI,oJ)
_(oH,cI)
var lK=_mz(z,'button',['bindcontact',13,'openType',1,'plain',2,'sessionFrom',3,'size',4,'style',5],[],e,s,gg)
var aL=_oz(z,19,e,s,gg)
_(lK,aL)
_(oH,lK)
_(xC,oH)
_(oB,xC)
_(r,oB)
return r
}