function(e,s,r,gg){
var z=gz$gwx_19()
var tGU=_n('view')
_rz(z,tGU,'class',0,e,s,gg)
var eHU=_v()
_(tGU,eHU)
var bIU=function(xKU,oJU,oLU,gg){
var cNU=_mz(z,'text',['bindtap',3,'class',1,'data-idx',2],[],xKU,oJU,gg)
var hOU=_oz(z,6,xKU,oJU,gg)
_(cNU,hOU)
_(oLU,cNU)
return oLU
}
eHU.wxXCkey=2
_2z(z,1,bIU,e,s,gg,eHU,'item','index','unique')
_(r,tGU)
var oPU=_n('view')
_rz(z,oPU,'class',7,e,s,gg)
var cQU=_mz(z,'swiper',['bindchange',8,'current',1,'style',2],[],e,s,gg)
var oRU=_n('swiper-item')
var lSU=_mz(z,'scroll-view',['scrollY',11,'style',1],[],e,s,gg)
var aTU=_n('view')
_rz(z,aTU,'class',13,e,s,gg)
var tUU=_n('view')
_rz(z,tUU,'class',14,e,s,gg)
var eVU=_n('view')
_rz(z,eVU,'class',15,e,s,gg)
var bWU=_mz(z,'image',['class',16,'mode',1,'src',2],[],e,s,gg)
_(eVU,bWU)
var oXU=_n('view')
_rz(z,oXU,'class',19,e,s,gg)
var xYU=_mz(z,'text',['class',20,'style',1],[],e,s,gg)
var oZU=_oz(z,22,e,s,gg)
_(xYU,oZU)
_(oXU,xYU)
var f1U=_oz(z,23,e,s,gg)
_(oXU,f1U)
_(eVU,oXU)
var c2U=_n('view')
_rz(z,c2U,'class',24,e,s,gg)
var h3U=_n('view')
_rz(z,h3U,'class',25,e,s,gg)
var o4U=_n('text')
_rz(z,o4U,'class',26,e,s,gg)
var c5U=_oz(z,27,e,s,gg)
_(o4U,c5U)
_(h3U,o4U)
var o6U=_n('text')
_rz(z,o6U,'class',28,e,s,gg)
var l7U=_oz(z,29,e,s,gg)
_(o6U,l7U)
_(h3U,o6U)
_(c2U,h3U)
var a8U=_n('view')
_rz(z,a8U,'class',30,e,s,gg)
var t9U=_n('text')
_rz(z,t9U,'class',31,e,s,gg)
var e0U=_oz(z,32,e,s,gg)
_(t9U,e0U)
_(a8U,t9U)
var bAV=_n('text')
_rz(z,bAV,'class',33,e,s,gg)
var oBV=_oz(z,34,e,s,gg)
_(bAV,oBV)
_(a8U,bAV)
_(c2U,a8U)
_(eVU,c2U)
_(tUU,eVU)
var xCV=_n('view')
_rz(z,xCV,'class',35,e,s,gg)
var oDV=_v()
_(xCV,oDV)
var fEV=function(hGV,cFV,oHV,gg){
var oJV=_mz(z,'view',['catchlongtap',39,'catchtap',1,'class',2,'data-idx',3,'style',4],[],hGV,cFV,gg)
var lKV=_n('view')
_rz(z,lKV,'class',44,hGV,cFV,gg)
var aLV=_n('view')
_rz(z,aLV,'class',45,hGV,cFV,gg)
var tMV=_mz(z,'view',['class',46,'style',1],[],hGV,cFV,gg)
var eNV=_oz(z,48,hGV,cFV,gg)
_(tMV,eNV)
_(aLV,tMV)
var bOV=_n('view')
_rz(z,bOV,'class',49,hGV,cFV,gg)
var oPV=_oz(z,50,hGV,cFV,gg)
_(bOV,oPV)
_(aLV,bOV)
_(lKV,aLV)
_(oJV,lKV)
var xQV=_n('view')
_rz(z,xQV,'class',51,hGV,cFV,gg)
var oRV=_n('view')
_rz(z,oRV,'class',52,hGV,cFV,gg)
var fSV=_n('view')
_rz(z,fSV,'class',53,hGV,cFV,gg)
var cTV=_oz(z,54,hGV,cFV,gg)
_(fSV,cTV)
_(oRV,fSV)
var hUV=_n('view')
_rz(z,hUV,'class',55,hGV,cFV,gg)
var oVV=_n('text')
_rz(z,oVV,'style',56,hGV,cFV,gg)
var cWV=_oz(z,57,hGV,cFV,gg)
_(oVV,cWV)
_(hUV,oVV)
var oXV=_oz(z,58,hGV,cFV,gg)
_(hUV,oXV)
_(oRV,hUV)
_(xQV,oRV)
_(oJV,xQV)
_(oHV,oJV)
return oHV
}
oDV.wxXCkey=2
_2z(z,37,fEV,e,s,gg,oDV,'dat','index','redpackNo')
_(tUU,xCV)
_(aTU,tUU)
var lYV=_n('view')
_rz(z,lYV,'style',59,e,s,gg)
var aZV=_v()
_(lYV,aZV)
if(_oz(z,60,e,s,gg)){aZV.wxVkey=1
var e2V=_mz(z,'navigator',['class',61,'hoverClass',1,'openType',2,'style',3,'url',4],[],e,s,gg)
var b3V=_n('view')
_rz(z,b3V,'class',66,e,s,gg)
var o4V=_oz(z,67,e,s,gg)
_(b3V,o4V)
_(e2V,b3V)
_(aZV,e2V)
}
var t1V=_v()
_(lYV,t1V)
if(_oz(z,68,e,s,gg)){t1V.wxVkey=1
var x5V=_n('view')
_rz(z,x5V,'style',69,e,s,gg)
_(t1V,x5V)
}
var o6V=_mz(z,'view',['bindtap',70,'class',1,'style',2],[],e,s,gg)
var f7V=_oz(z,73,e,s,gg)
_(o6V,f7V)
_(lYV,o6V)
aZV.wxXCkey=1
t1V.wxXCkey=1
_(aTU,lYV)
_(lSU,aTU)
_(oRU,lSU)
_(cQU,oRU)
var c8V=_n('swiper-item')
var h9V=_mz(z,'scroll-view',['scrollY',74,'style',1],[],e,s,gg)
var o0V=_n('view')
_rz(z,o0V,'class',76,e,s,gg)
var cAW=_n('view')
_rz(z,cAW,'class',77,e,s,gg)
var oBW=_n('view')
_rz(z,oBW,'class',78,e,s,gg)
var lCW=_mz(z,'image',['class',79,'mode',1,'src',2],[],e,s,gg)
_(oBW,lCW)
var aDW=_n('view')
_rz(z,aDW,'class',82,e,s,gg)
var tEW=_mz(z,'text',['class',83,'style',1],[],e,s,gg)
var eFW=_oz(z,85,e,s,gg)
_(tEW,eFW)
_(aDW,tEW)
var bGW=_oz(z,86,e,s,gg)
_(aDW,bGW)
_(oBW,aDW)
var oHW=_n('view')
_rz(z,oHW,'class',87,e,s,gg)
var xIW=_n('view')
_rz(z,xIW,'class',88,e,s,gg)
var oJW=_n('text')
_rz(z,oJW,'class',89,e,s,gg)
var fKW=_oz(z,90,e,s,gg)
_(oJW,fKW)
_(xIW,oJW)
var cLW=_n('text')
_rz(z,cLW,'class',91,e,s,gg)
var hMW=_oz(z,92,e,s,gg)
_(cLW,hMW)
_(xIW,cLW)
_(oHW,xIW)
var oNW=_n('view')
_rz(z,oNW,'class',93,e,s,gg)
var cOW=_n('text')
_rz(z,cOW,'class',94,e,s,gg)
var oPW=_oz(z,95,e,s,gg)
_(cOW,oPW)
_(oNW,cOW)
var lQW=_n('text')
_rz(z,lQW,'class',96,e,s,gg)
var aRW=_oz(z,97,e,s,gg)
_(lQW,aRW)
_(oNW,lQW)
_(oHW,oNW)
_(oBW,oHW)
_(cAW,oBW)
var tSW=_mz(z,'view',['class',98,'style',1],[],e,s,gg)
var eTW=_v()
_(tSW,eTW)
var bUW=function(xWW,oVW,oXW,gg){
var cZW=_mz(z,'view',['bindtap',103,'class',1,'data-idx',2,'style',3],[],xWW,oVW,gg)
var h1W=_n('view')
_rz(z,h1W,'class',107,xWW,oVW,gg)
var o2W=_n('view')
_rz(z,o2W,'class',108,xWW,oVW,gg)
var c3W=_mz(z,'image',['class',109,'src',1],[],xWW,oVW,gg)
_(o2W,c3W)
var o4W=_n('view')
_rz(z,o4W,'style',111,xWW,oVW,gg)
var l5W=_n('view')
_rz(z,l5W,'class',112,xWW,oVW,gg)
var a6W=_oz(z,113,xWW,oVW,gg)
_(l5W,a6W)
_(o4W,l5W)
var t7W=_n('view')
_rz(z,t7W,'class',114,xWW,oVW,gg)
var e8W=_oz(z,115,xWW,oVW,gg)
_(t7W,e8W)
_(o4W,t7W)
_(o2W,o4W)
_(h1W,o2W)
_(cZW,h1W)
var b9W=_n('view')
_rz(z,b9W,'class',116,xWW,oVW,gg)
var o0W=_n('view')
_rz(z,o0W,'class',117,xWW,oVW,gg)
var xAX=_n('view')
_rz(z,xAX,'class',118,xWW,oVW,gg)
var oBX=_oz(z,119,xWW,oVW,gg)
_(xAX,oBX)
_(o0W,xAX)
var fCX=_n('view')
_rz(z,fCX,'class',120,xWW,oVW,gg)
var cDX=_oz(z,121,xWW,oVW,gg)
_(fCX,cDX)
_(o0W,fCX)
_(b9W,o0W)
_(cZW,b9W)
_(oXW,cZW)
return oXW
}
eTW.wxXCkey=2
_2z(z,101,bUW,e,s,gg,eTW,'dat','index','redpackNo')
_(cAW,tSW)
_(o0V,cAW)
var hEX=_n('view')
_rz(z,hEX,'style',122,e,s,gg)
var oFX=_v()
_(hEX,oFX)
if(_oz(z,123,e,s,gg)){oFX.wxVkey=1
var oHX=_mz(z,'navigator',['class',124,'hoverClass',1,'openType',2,'style',3,'url',4],[],e,s,gg)
var lIX=_n('view')
_rz(z,lIX,'class',129,e,s,gg)
var aJX=_oz(z,130,e,s,gg)
_(lIX,aJX)
_(oHX,lIX)
_(oFX,oHX)
}
var cGX=_v()
_(hEX,cGX)
if(_oz(z,131,e,s,gg)){cGX.wxVkey=1
var tKX=_n('view')
_rz(z,tKX,'style',132,e,s,gg)
_(cGX,tKX)
}
var eLX=_mz(z,'view',['bindtap',133,'class',1,'style',2],[],e,s,gg)
var bMX=_oz(z,136,e,s,gg)
_(eLX,bMX)
_(hEX,eLX)
oFX.wxXCkey=1
cGX.wxXCkey=1
_(o0V,hEX)
_(h9V,o0V)
_(c8V,h9V)
_(cQU,c8V)
_(oPU,cQU)
_(r,oPU)
var oNX=_mz(z,'modal',['bindcancel',137,'bindconfirm',1,'cancelText',2,'confirmText',3,'hidden',4,'title',5],[],e,s,gg)
var xOX=_n('view')
var oPX=_oz(z,143,e,s,gg)
_(xOX,oPX)
_(oNX,xOX)
var fQX=_n('view')
_rz(z,fQX,'style',144,e,s,gg)
var cRX=_oz(z,145,e,s,gg)
_(fQX,cRX)
_(oNX,fQX)
_(r,oNX)
var hSX=_mz(z,'auth',['bindauthevent',146,'needAuth',1],[],e,s,gg)
_(r,hSX)
return r
}