function(e,s,r,gg){
var z=gz$gwx_11()
var cBL=_n('view')
_rz(z,cBL,'class',0,e,s,gg)
var hCL=_mz(z,'scroll-view',['scrollY',1,'style',1],[],e,s,gg)
var oDL=_n('view')
_rz(z,oDL,'class',3,e,s,gg)
var cEL=_n('view')
_rz(z,cEL,'class',4,e,s,gg)
var oFL=_n('view')
_rz(z,oFL,'style',5,e,s,gg)
var tIL=_n('view')
_rz(z,tIL,'style',6,e,s,gg)
var eJL=_v()
_(tIL,eJL)
var bKL=function(xML,oLL,oNL,gg){
var cPL=_n('view')
_rz(z,cPL,'style',10,xML,oLL,gg)
var hQL=_mz(z,'view',['bindtap',11,'class',1,'data-idx',2,'style',3],[],xML,oLL,gg)
var oRL=_n('view')
_rz(z,oRL,'class',15,xML,oLL,gg)
var cSL=_n('view')
_rz(z,cSL,'class',16,xML,oLL,gg)
var oTL=_oz(z,17,xML,oLL,gg)
_(cSL,oTL)
_(oRL,cSL)
var lUL=_mz(z,'image',['class',18,'src',1],[],xML,oLL,gg)
_(oRL,lUL)
_(hQL,oRL)
_(cPL,hQL)
var aVL=_mz(z,'view',['class',20,'hidden',1],[],xML,oLL,gg)
var tWL=_n('text')
var eXL=_oz(z,22,xML,oLL,gg)
_(tWL,eXL)
_(aVL,tWL)
_(cPL,aVL)
_(oNL,cPL)
return oNL
}
eJL.wxXCkey=2
_2z(z,8,bKL,e,s,gg,eJL,'ques','index','sort')
_(oFL,tIL)
var lGL=_v()
_(oFL,lGL)
if(_oz(z,23,e,s,gg)){lGL.wxVkey=1
var bYL=_mz(z,'button',['openType',24,'sessionFrom',1,'style',2,'type',3],[],e,s,gg)
var oZL=_mz(z,'image',['src',28,'style',1],[],e,s,gg)
_(bYL,oZL)
var x1L=_n('text')
_rz(z,x1L,'style',30,e,s,gg)
var o2L=_oz(z,31,e,s,gg)
_(x1L,o2L)
_(bYL,x1L)
_(lGL,bYL)
}
var aHL=_v()
_(oFL,aHL)
if(_oz(z,32,e,s,gg)){aHL.wxVkey=1
var f3L=_mz(z,'view',['bindtap',33,'class',1],[],e,s,gg)
var c4L=_oz(z,35,e,s,gg)
_(f3L,c4L)
_(aHL,f3L)
}
lGL.wxXCkey=1
aHL.wxXCkey=1
_(cEL,oFL)
_(oDL,cEL)
var h5L=_n('view')
_rz(z,h5L,'class',36,e,s,gg)
var c7L=_mz(z,'view',['class',37,'style',1],[],e,s,gg)
var o8L=_oz(z,39,e,s,gg)
_(c7L,o8L)
_(h5L,c7L)
var l9L=_n('view')
_rz(z,l9L,'style',40,e,s,gg)
_(h5L,l9L)
var o6L=_v()
_(h5L,o6L)
if(_oz(z,41,e,s,gg)){o6L.wxVkey=1
var a0L=_mz(z,'view',['bindtap',42,'class',1],[],e,s,gg)
var tAM=_oz(z,44,e,s,gg)
_(a0L,tAM)
_(o6L,a0L)
var eBM=_n('view')
_rz(z,eBM,'style',45,e,s,gg)
_(o6L,eBM)
}
var bCM=_mz(z,'view',['bindtap',46,'class',1],[],e,s,gg)
var oDM=_oz(z,48,e,s,gg)
_(bCM,oDM)
_(h5L,bCM)
o6L.wxXCkey=1
_(oDL,h5L)
_(hCL,oDL)
_(cBL,hCL)
_(r,cBL)
return r
}