function(e,s,r,gg){
var z=gz$gwx_17()
var oTR=_mz(z,'view',['class',0,'style',1],[],e,s,gg)
_(r,oTR)
var xUR=_n('view')
_rz(z,xUR,'class',2,e,s,gg)
var oVR=_n('view')
_rz(z,oVR,'class',3,e,s,gg)
var fWR=_mz(z,'image',['bindtap',4,'class',1,'src',2],[],e,s,gg)
_(oVR,fWR)
var cXR=_n('view')
_rz(z,cXR,'class',7,e,s,gg)
var hYR=_oz(z,8,e,s,gg)
_(cXR,hYR)
_(oVR,cXR)
_(xUR,oVR)
_(r,xUR)
var oZR=_mz(z,'view',['bindtap',9,'class',1],[],e,s,gg)
var c1R=_n('view')
_rz(z,c1R,'class',11,e,s,gg)
var o2R=_n('view')
_rz(z,o2R,'class',12,e,s,gg)
var l3R=_n('view')
_rz(z,l3R,'class',13,e,s,gg)
var a4R=_mz(z,'image',['mode',14,'src',1],[],e,s,gg)
_(l3R,a4R)
_(o2R,l3R)
var t5R=_n('view')
_rz(z,t5R,'class',16,e,s,gg)
var e6R=_oz(z,17,e,s,gg)
_(t5R,e6R)
_(o2R,t5R)
_(c1R,o2R)
var b7R=_n('view')
_rz(z,b7R,'class',18,e,s,gg)
var o8R=_n('view')
_rz(z,o8R,'class',19,e,s,gg)
var x9R=_oz(z,20,e,s,gg)
_(o8R,x9R)
_(b7R,o8R)
_(c1R,b7R)
_(oZR,c1R)
_(r,oZR)
var o0R=_mz(z,'view',['bindtap',21,'class',1],[],e,s,gg)
var fAS=_n('view')
_rz(z,fAS,'class',23,e,s,gg)
var cBS=_n('view')
_rz(z,cBS,'class',24,e,s,gg)
var hCS=_n('view')
_rz(z,hCS,'class',25,e,s,gg)
var oDS=_mz(z,'image',['mode',26,'src',1],[],e,s,gg)
_(hCS,oDS)
_(cBS,hCS)
var cES=_n('view')
_rz(z,cES,'class',28,e,s,gg)
var oFS=_oz(z,29,e,s,gg)
_(cES,oFS)
_(cBS,cES)
_(fAS,cBS)
var lGS=_n('view')
_rz(z,lGS,'class',30,e,s,gg)
_(fAS,lGS)
_(o0R,fAS)
_(r,o0R)
var aHS=_n('view')
_rz(z,aHS,'class',31,e,s,gg)
var eJS=_mz(z,'view',['bindtap',32,'class',1],[],e,s,gg)
var bKS=_n('view')
_rz(z,bKS,'class',34,e,s,gg)
var oLS=_n('view')
_rz(z,oLS,'class',35,e,s,gg)
var xMS=_mz(z,'image',['mode',36,'src',1],[],e,s,gg)
_(oLS,xMS)
_(bKS,oLS)
var oNS=_n('view')
_rz(z,oNS,'class',38,e,s,gg)
var fOS=_oz(z,39,e,s,gg)
_(oNS,fOS)
_(bKS,oNS)
_(eJS,bKS)
var cPS=_n('view')
_rz(z,cPS,'class',40,e,s,gg)
_(eJS,cPS)
_(aHS,eJS)
var tIS=_v()
_(aHS,tIS)
if(_oz(z,41,e,s,gg)){tIS.wxVkey=1
var hQS=_mz(z,'button',['bindcontact',42,'class',1,'openType',2,'sessionFrom',3,'style',4],[],e,s,gg)
var oRS=_n('view')
_rz(z,oRS,'class',47,e,s,gg)
var cSS=_n('view')
_rz(z,cSS,'class',48,e,s,gg)
var oTS=_mz(z,'image',['mode',49,'src',1],[],e,s,gg)
_(cSS,oTS)
_(oRS,cSS)
var lUS=_n('view')
_rz(z,lUS,'class',51,e,s,gg)
var aVS=_oz(z,52,e,s,gg)
_(lUS,aVS)
_(oRS,lUS)
_(hQS,oRS)
var tWS=_n('view')
_rz(z,tWS,'class',53,e,s,gg)
var bYS=_n('view')
_rz(z,bYS,'class',54,e,s,gg)
var oZS=_oz(z,55,e,s,gg)
_(bYS,oZS)
_(tWS,bYS)
var eXS=_v()
_(tWS,eXS)
if(_oz(z,56,e,s,gg)){eXS.wxVkey=1
var x1S=_n('view')
_rz(z,x1S,'class',57,e,s,gg)
_(eXS,x1S)
}
eXS.wxXCkey=1
_(hQS,tWS)
_(tIS,hQS)
}
var o2S=_mz(z,'button',['bindcontact',58,'class',1,'openType',2,'sessionFrom',3,'style',4],[],e,s,gg)
var f3S=_n('view')
_rz(z,f3S,'class',63,e,s,gg)
var c4S=_n('view')
_rz(z,c4S,'class',64,e,s,gg)
var h5S=_mz(z,'image',['mode',65,'src',1],[],e,s,gg)
_(c4S,h5S)
_(f3S,c4S)
var o6S=_n('view')
_rz(z,o6S,'class',67,e,s,gg)
var c7S=_oz(z,68,e,s,gg)
_(o6S,c7S)
_(f3S,o6S)
_(o2S,f3S)
var o8S=_n('view')
_rz(z,o8S,'class',69,e,s,gg)
_(o2S,o8S)
_(aHS,o2S)
tIS.wxXCkey=1
_(r,aHS)
var l9S=_mz(z,'auth',['bindauthevent',70,'needAuth',1],[],e,s,gg)
_(r,l9S)
return r
}