function(e,s,r,gg){
var z=gz$gwx_25()
var cTGB=_n('view')
_rz(z,cTGB,'class',0,e,s,gg)
var hUGB=_v()
_(cTGB,hUGB)
if(_oz(z,1,e,s,gg)){hUGB.wxVkey=1
var oVGB=_n('view')
_rz(z,oVGB,'class',2,e,s,gg)
var cWGB=_n('view')
_rz(z,cWGB,'class',3,e,s,gg)
var oXGB=_v()
_(cWGB,oXGB)
if(_oz(z,4,e,s,gg)){oXGB.wxVkey=1
var lYGB=_mz(z,'view',['bindtap',5,'class',1],[],e,s,gg)
var aZGB=_mz(z,'image',['class',7,'src',1],[],e,s,gg)
_(lYGB,aZGB)
_(oXGB,lYGB)
}
var t1GB=_mz(z,'image',['bindload',9,'bindtap',1,'class',2,'mode',3,'src',4],[],e,s,gg)
_(cWGB,t1GB)
oXGB.wxXCkey=1
_(oVGB,cWGB)
var e2GB=_n('view')
_rz(z,e2GB,'style',14,e,s,gg)
var b3GB=_mz(z,'button',['bindtap',15,'class',1,'hidden',2],[],e,s,gg)
var o4GB=_mz(z,'image',['mode',18,'src',1,'style',2],[],e,s,gg)
_(b3GB,o4GB)
var x5GB=_oz(z,21,e,s,gg)
_(b3GB,x5GB)
_(e2GB,b3GB)
var o6GB=_mz(z,'button',['class',22,'openType',1],[],e,s,gg)
var f7GB=_mz(z,'image',['mode',24,'src',1,'style',2],[],e,s,gg)
_(o6GB,f7GB)
var c8GB=_oz(z,27,e,s,gg)
_(o6GB,c8GB)
_(e2GB,o6GB)
_(oVGB,e2GB)
var h9GB=_mz(z,'view',['catchtap',28,'class',1,'style',2],[],e,s,gg)
var o0GB=_n('text')
_rz(z,o0GB,'style',31,e,s,gg)
var cAHB=_oz(z,32,e,s,gg)
_(o0GB,cAHB)
_(h9GB,o0GB)
var oBHB=_mz(z,'image',['src',33,'style',1],[],e,s,gg)
_(h9GB,oBHB)
_(oVGB,h9GB)
_(hUGB,oVGB)
}
var lCHB=_n('view')
_rz(z,lCHB,'class',35,e,s,gg)
var aDHB=_oz(z,36,e,s,gg)
_(lCHB,aDHB)
_(cTGB,lCHB)
hUGB.wxXCkey=1
_(r,cTGB)
var tEHB=_mz(z,'modal',['bindconfirm',37,'confirmText',1,'hidden',2,'noCancel',3,'style',4,'title',5],[],e,s,gg)
_(r,tEHB)
var fSGB=_v()
_(r,fSGB)
if(_oz(z,43,e,s,gg)){fSGB.wxVkey=1
var eFHB=_mz(z,'view',['bindtap',44,'class',1,'style',2],[],e,s,gg)
var bGHB=_n('view')
_rz(z,bGHB,'class',47,e,s,gg)
var oHHB=_n('view')
var xIHB=_oz(z,48,e,s,gg)
_(oHHB,xIHB)
_(bGHB,oHHB)
_(eFHB,bGHB)
_(fSGB,eFHB)
}
var oJHB=_mz(z,'auth',['bindauthevent',49,'needAuth',1],[],e,s,gg)
_(r,oJHB)
fSGB.wxXCkey=1
return r
}