function(e,s,r,gg){
var z=gz$gwx_26()
var cLHB=_n('view')
_rz(z,cLHB,'class',0,e,s,gg)
var hMHB=_mz(z,'view',['class',1,'style',1],[],e,s,gg)
var oNHB=_mz(z,'image',['bindtap',3,'mode',1,'src',2,'style',3],[],e,s,gg)
_(hMHB,oNHB)
_(cLHB,hMHB)
var cOHB=_n('view')
_rz(z,cOHB,'class',7,e,s,gg)
var oPHB=_n('view')
_rz(z,oPHB,'class',8,e,s,gg)
var lQHB=_oz(z,9,e,s,gg)
_(oPHB,lQHB)
var aRHB=_mz(z,'text',['bindtap',10,'style',1],[],e,s,gg)
var tSHB=_oz(z,12,e,s,gg)
_(aRHB,tSHB)
_(oPHB,aRHB)
_(cOHB,oPHB)
var eTHB=_mz(z,'view',['bindtap',13,'class',1],[],e,s,gg)
var bUHB=_oz(z,15,e,s,gg)
_(eTHB,bUHB)
_(cOHB,eTHB)
_(cLHB,cOHB)
_(r,cLHB)
return r
}